SQLALCHEMY_DATABASE_URI = 'postgresql+psycopg2://postgres:909909@postgres-db:5433/devOps-db'

SECRET_KEY = 'qwerty1234'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_ECHO = False
ADMIN_ROLE_ID = 1
MODER_ROLE_ID = 2
FLASK_APP='app.py'
FLASK_ENV='development'
FLASK_DEBUG=1
