version: '3.3'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: devOps-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 909909
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data

  flaskproj: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Dcompose-flask
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:909909@postgres-db:5432/devOps-db
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --debug

volumes:
  postgres-data:

